//<PROJECT>_<PATH>_<FILE>_H_
#ifndef CPP2_S21_CONTAINERS_SRC_S21_CONTAINERS_H_  //
#define CPP2_S21_CONTAINERS_SRC_S21_CONTAINERS_H_ 
#include "s21_vector.h"
#include "s21_list.h"
#endif //CPP2_S21_CONTAINERS_SRC_S21_CONTAINERS_H_ 
